/**
 * Robots.txt Generator — Next.js App Router convention
 *
 * Allows all crawlers, blocks admin routes, references sitemap.
 * /api/og is explicitly allowed so social crawlers (Twitter, Facebook,
 * LinkedIn, Slack) can fetch OpenGraph images generated by the Edge route.
 */

import type { MetadataRoute } from "next";

const SITE_URL = process.env.NEXT_PUBLIC_SITE_URL ?? "https://mizoamin.com";

export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: "*",
        allow: ["/", "/api/og"],
        disallow: [
          "/secret-control-room/",
          "/api/generate-blog",
          "/_next/",
        ],
      },
    ],
    sitemap: `${SITE_URL}/sitemap.xml`,
  };
}
